# Generated by Django 6.0.4 on 2026-04-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot_origine', models.CharField(max_length=200, verbose_name='Mot ou phrase')),
                ('langue_cible', models.CharField(choices=[('FR', 'Français'), ('BAO', 'Baoulé'), ('DIO', 'Dioula'), ('LSI', 'Langue des Signes')], max_length=10)),
                ('resultat_traduction', models.TextField()),
                ('video_signe', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
