# Generated by Django 6.0.4 on 2026-04-28 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nzassa_app', '0002_badge_culturalexperience_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('channel', models.CharField(choices=[('coach', 'Coach IA'), ('landing', 'Accueil')], default='coach', max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('last_remote_response_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selected_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_conversations', to='nzassa_app.language')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('assistant', 'Assistant')], max_length=20)),
                ('content', models.TextField()),
                ('used_openai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='nzassa_app.coachconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearnedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('owner_key', models.CharField(db_index=True, max_length=80)),
                ('language_label', models.CharField(blank=True, max_length=120)),
                ('word', models.CharField(max_length=120)),
                ('normalized_word', models.CharField(db_index=True, max_length=120)),
                ('meaning', models.CharField(blank=True, max_length=255)),
                ('example', models.TextField(blank=True)),
                ('pronunciation_hint', models.CharField(blank=True, max_length=255)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('times_practiced', models.PositiveIntegerField(default=0)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('mastery_level', models.PositiveIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_words', to='nzassa_app.coachconversation')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learned_words', to='nzassa_app.language')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learned_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mastery_level', '-times_seen', 'word'],
                'unique_together': {('owner_key', 'normalized_word', 'language_label')},
            },
        ),
        migrations.CreateModel(
            name='PronunciationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_word', models.CharField(max_length=120)),
                ('transcript', models.CharField(blank=True, max_length=255)),
                ('score', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronunciation_attempts', to='nzassa_app.coachconversation')),
                ('learned_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pronunciation_attempts', to='nzassa_app.learnedword')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
