from django.urls import include, path

from .api import DashboardAPIView, RecommendationAPIView, router as api_router

from .views import (
    NzassaLoginView,
    accueil,
    ai_coach,
    audio_add,
    audio_library,
    book_add,
    book_detail,
    book_download,
    book_favorite,
    book_read,
    certificate_detail,
    certificate_issue,
    certificate_pdf,
    coach_ai_chat,
    coach_pronunciation_feedback,
    course_catalog,
    course_detail,
    cultural_ai,
    dashboard,
    discussion_feed,
    discussion_profile,
    ethnicity_map,
    enroll_course,
    friend_accept,
    friend_request,
    games_hub,
    group_create,
    group_detail,
    group_join,
    chercher_mot,
    immersion_vr,
    landing_ai_chat,
    lesson_detail,
    library,
    logout_view,
    learning_groups,
    messages_inbox,
    micro_lessons,
    mobile_money_payment,
    notifications_center,
    offline_add,
    offline_center,
    post_comment,
    post_like,
    pricing,
    reconnaissance_signes,
    register,
    school_create,
    short_video_add,
    short_video_feed,
    short_video_like,
    story_add,
    story_comment,
    story_detail,
    story_like,
    story_list,
    teacher_dashboard,
)

urlpatterns = [
    path("", accueil, name="accueil"),
    path("histoires/", story_list, name="story_list"),
    path("histoires/ajouter/", story_add, name="story_add"),
    path("histoires/<slug:slug>/", story_detail, name="story_detail"),
    path("histoires/<slug:slug>/like/", story_like, name="story_like"),
    path("histoires/<slug:slug>/commenter/", story_comment, name="story_comment"),
    path("librairie/", library, name="library"),
    path("librairie/ajouter/", book_add, name="book_add"),
    path("librairie/<slug:slug>/", book_detail, name="book_detail"),
    path("librairie/<slug:slug>/lire/", book_read, name="book_read"),
    path("librairie/<slug:slug>/telecharger/", book_download, name="book_download"),
    path("librairie/<slug:slug>/favori/", book_favorite, name="book_favorite"),
    path("audio/", audio_library, name="audio_library"),
    path("audio/ajouter/", audio_add, name="audio_add"),
    path("discussion/", discussion_feed, name="discussion_feed"),
    path("discussion/groupes/", learning_groups, name="learning_groups"),
    path("discussion/groupes/creer/", group_create, name="group_create"),
    path("discussion/groupes/<slug:slug>/", group_detail, name="group_detail"),
    path("discussion/groupes/<slug:slug>/rejoindre/", group_join, name="group_join"),
    path("discussion/messages/", messages_inbox, name="messages_inbox"),
    path("discussion/profil/<str:username>/", discussion_profile, name="discussion_profile"),
    path("discussion/profil/<str:username>/ami/", friend_request, name="friend_request"),
    path("discussion/amis/<int:connection_id>/accepter/", friend_accept, name="friend_accept"),
    path("discussion/posts/<int:post_id>/like/", post_like, name="post_like"),
    path("discussion/posts/<int:post_id>/commenter/", post_comment, name="post_comment"),
    path("notifications/", notifications_center, name="notifications"),
    path("carte-ethnies/", ethnicity_map, name="ethnicity_map"),
    path("shorts/", short_video_feed, name="short_video_feed"),
    path("shorts/ajouter/", short_video_add, name="short_video_add"),
    path("shorts/<slug:slug>/like/", short_video_like, name="short_video_like"),
    path("offline/", offline_center, name="offline_center"),
    path("offline/ajouter/", offline_add, name="offline_add"),
    path("formateur/", teacher_dashboard, name="teacher_dashboard"),
    path("formateur/ecoles/creer/", school_create, name="school_create"),
    path("certificats/<str:code>/", certificate_detail, name="certificate_detail"),
    path("certificats/<str:code>/pdf/", certificate_pdf, name="certificate_pdf"),
    path("micro-lecons/", micro_lessons, name="micro_lessons"),
    path("paiement/mobile-money/", mobile_money_payment, name="mobile_money_payment"),
    path("jeux/", games_hub, name="games_hub"),
    path("assistant-culturel/", cultural_ai, name="cultural_ai"),
    path("coach-ia/", ai_coach, name="ai_coach"),
    path("api/coach-ia/chat/", coach_ai_chat, name="coach_ai_chat"),
    path("api/coach-ia/prononciation/", coach_pronunciation_feedback, name="coach_pronunciation_feedback"),
    path("api/v1/", include(api_router.urls)),
    path("api/v1/dashboard/", DashboardAPIView.as_view(), name="api_dashboard"),
    path("api/v1/recommendations/", RecommendationAPIView.as_view(), name="api_recommendations"),
    path("parcours/", course_catalog, name="course_catalog"),
    path("parcours/<slug:slug>/", course_detail, name="course_detail"),
    path("parcours/<slug:slug>/inscription/", enroll_course, name="enroll_course"),
    path("parcours/<slug:course_slug>/certificat/", certificate_issue, name="certificate_issue"),
    path("parcours/<slug:course_slug>/lecons/<int:lesson_id>/", lesson_detail, name="lesson_detail"),
    path("dashboard/", dashboard, name="dashboard"),
    path("tarifs/", pricing, name="pricing"),
    path("connexion/", NzassaLoginView.as_view(), name="login"),
    path("inscription/", register, name="register"),
    path("deconnexion/", logout_view, name="logout"),
    path("ia-signes/", reconnaissance_signes, name="ia_signes"),
    path("immersion/", immersion_vr, name="immersion"),
    path("chercher/", chercher_mot, name="chercher_mot"),
    path("api/landing-ai/", landing_ai_chat, name="landing_ai_chat"),
]
